# Generated by Django 2.2 on 2020-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200320_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='are_you_a_social_media_marketeer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='are_you_an_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
