# Generated by Django 2.2 on 2020-03-11 16:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=500),
        ),
    ]
