# Generated by Django 2.2 on 2020-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Choose a Category Image', null=True, upload_to='category_images/'),
        ),
    ]
