# Generated by Django 2.2 on 2020-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Choose a Category Image', null=True, upload_to='master_category_images/'),
        ),
    ]
