# Generated by Django 2.2 on 2020-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_mastercategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Check the bullet point if it is a demo lesson'),
        ),
    ]
