# Generated by Django 2.2 on 2020-03-12 15:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200312_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(default='Unset'),
        ),
    ]
