# Generated by Django 2.2 on 2020-03-13 19:47

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200313_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter the entire course outflow just like you would in a word document'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Only set this to False, when the course is under making and you wish not to make it public'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(help_text='Medium/Languages used in the lesson videos', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(help_text='Level can be, 1/2/3 or Beginner/Intermidiate/Advance', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='outcome',
            field=models.CharField(help_text='Outcome/Achievements after successful completion of the course', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(help_text='Price of the course, to be entered in Indian Currency', validators=[django.core.validators.MinValueValidator(9.99)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.CharField(help_text='Prequisites for enroll in the Course', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(help_text='This field expects an image file, 480x360 is ideal', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Updating course regularly ensures better reach'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Enter the link to the video from any streaming platform, Vimeo Preffered', max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(help_text='Enter video clip duration in Minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text="Enter the Lesson's title", max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Vimeo Video is preffered since it ensure data protection', max_length=500),
        ),
    ]
