# Generated by Django 2.2 on 2020-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='enable_access',
            field=models.BooleanField(default=False, help_text='Making this True will enable the user to access the course, after payment is recieved'),
        ),
    ]
