# Generated by Django 2.2 on 2020-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20200421_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='news',
            field=models.CharField(blank=True, default='Welcome! Discover your learning track, you may contact us for great discounts', help_text='All lastest news here', max_length=300, null=True),
        ),
    ]
