# Generated by Django 2.2 on 2020-03-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
