# Generated by Django 2.2 on 2020-03-19 09:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20200319_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='faqs',
            field=ckeditor.fields.RichTextField(default='faqs', help_text='Enter some FAQs'),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(default='privacy', help_text='Enter your Privacy Policy'),
        ),
    ]
