# Generated by Django 2.2 on 2020-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_auto_20200319_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter the unique code here e.g COURSELOVE20', max_length=20)),
                ('value', models.IntegerField(default=0, help_text='Enter discount in percentage')),
            ],
        ),
    ]
