# Generated by Django 2.2 on 2020-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Enter the payment ID in which you want to get payments', max_length=300),
        ),
    ]
