# Generated by Django 2.2 on 2020-04-20 12:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200420_1825'),
        ('root', '0010_pageinfo_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': 'Enrollments', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AddField(
            model_name='discount',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='currency',
            field=models.CharField(default='₹', max_length=20),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='email',
            field=models.CharField(default='Email not set', help_text='Enter your company/support email', max_length=100),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='home_banner',
            field=ckeditor.fields.RichTextField(default='The flashy tagline goes here', help_text='Enter the tagline in the home banner', max_length=2000),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='tag_1',
            field=ckeditor.fields.RichTextField(default='Your homepage Tagline 1 goes here !', help_text='You fancy webpage features must go in here', max_length=500),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='tag_2',
            field=ckeditor.fields.RichTextField(default='Your homepage Tagline 2 goes here !', help_text='You fancy webpage features must go in here', max_length=500),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='tag_3',
            field=ckeditor.fields.RichTextField(default='Your homepage Tagline 3 goes here !', help_text='You fancy webpage features must go in here', max_length=500),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='title',
            field=models.CharField(default='Institute of Academic Excellence', help_text='Enter the name of your page', max_length=300),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='services',
            field=ckeditor.fields.RichTextField(help_text='Enter the range of services provided to users'),
        ),
    ]
